import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import Header from "./ui/header";
import { DevContextProvider } from "./ui/components/devnamesprovider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <DevContextProvider>
        <body className={inter.className + " flex flex-col gap-4 antialiased"}>
          <Header />
          {children}
        </body>
      </DevContextProvider>
    </html>
  );
}
